### ISSUE TITLE
lmao the whole client is shit

### ISSUE THREAD

**Issue by Tigermouthbear** [chell-dev/Osiris#55]
lmao, you skidded kami and made it worse. you should have just found and replaced the words "KAMI"

**Comment by cookiedragon234** [comment]
:/

**Comment by Crystallinqq** [comment]
kami with le herocode gui

**Comment by DarkiBoi** [comment]
Are you mentally deranged

**Comment by S-B99** [comment]
accurate lmao

**Comment by hhhhwwe** [comment]
tranny tranny tranny alert

**Comment by S-B99** [comment]
I don't think tiger is trans? Either way that's a disrespectful term to use, especially in a professional setting such as this.

**Comment by S-B99** [comment]
lol finz0 mad

**Comment by hhhhwwe** [comment]
cry more about me calling you a tranny

**Comment by S-B99** [comment]
https://github.com/codefellows/code-of-conduct

**Comment by hhhhwwe** [comment]
cry

**Comment by S-B99** [comment]
I'm not seeing a concrete argument really. Imagine arguing in github issues. 

Too scared to actually confront me? My contact into is on my profile.

**Comment by hhhhwwe** [comment]
oh yeah i forgot that it is
let me get in contact tranny

**Comment by hhhhwwe** [comment]
you can try to silence me on kami blue github

**Comment by S-B99** [comment]
I closed the issues as invalid as they did not follow the issue template and as such were invalid. Neither of them were module bugs.

**Comment by hhhhwwe** [comment]
bruh i was reporting a bug. it was the name of the client

**Comment by hhhhwwe** [comment]
"Also, as I said before, I don't endorse the usage of slurs."

**Comment by S-B99** [comment]
Yes, that it was I said. And a bug is unintentional behavior of the software. The program is completely intentionally called KAMI Blue.

**Comment by hhhhwwe** [comment]
it has to be a mistake I would call my phone a "Steve Jobs phone" because he made it or at least thought of the idea for his phone. So I would call your client TRANNY BLUE because you made the client and you so happen to be a tranny.

**Comment by S-B99** [comment]
I don't? Where did I say I was lol? 

Also if you did, then everyone would call their iPhones "Steve Jobs Phones"

**Comment by hhhhwwe** [comment]
What? I thought you said you are a tranny lol?

Also why the hell are you taking this so seriously this is a block game cheat GITHUB lmao

**Comment by S-B99** [comment]
Yes. Github is a professional setting. If you want to go throw insults at someone for fun, then contact me. 

Also I never said that.

**Comment by hhhhwwe** [comment]
What? you clearly said it when you joined a discord call?

**Comment by hhhhwwe** [comment]
oh also TRANNY

**Comment by S-B99** [comment]
> oh also TRANNY

wow dude, that was such a great argument. Say it again. It really hurt my feeings :((

oh no i got called a tranny i'm so sad :c

**Comment by S-B99** [comment]
> What? you clearly said it when you joined a discord call?

please link the github issue where i said that

**Comment by hhhhwwe** [comment]
block game cheat dev is cringe

**Comment by hhhhwwe** [comment]
also you did not say that in a github soooo

**Comment by S-B99** [comment]
Therefor I am not. 

I'm done here. You've been really rude and unprofessional, and this isn't going anywhere, nor would it have. Go find somewhere else to waste your time. 

It doesn't help anyone to call someone a slur in github issues of all places.

**Comment by Tigermouthbear** [comment]
@FINZ0 can you at least give credit to the people you skidded from?

**Comment by S-B99** [comment]
^ LOL

**Comment by S-B99** [comment]
he tried to claim he wrote kami in my pull request here

**Comment by Tigermouthbear** [comment]
lmao :clown_face:
